from tkinter import *
import os
def f():
    def save():
        a = t.get()
        f = open((a + '.txt'), 'w')
        f.write(a)
        f.close()
        return
def infosearch():
    root.destroy()
    root1 = Tk()
    f = open('name.txt', 'a')
    root1.geometry(
        "500x500+400+100")  # the window size geometry("window width x window height + position right + position down")
    root1.title("Soda machine")
    Title = Label(root1, text="Client Information")
    Title.pack()  # put in the middle
    Paragraph1 = Label(root1, text="\nFirst name\n")
    Paragraph1.place(x=25, y=25)
    e1 = Entry(root1, text="")
    e1.place(x=25, y=60)  # can change stuff place
    paragraph2 = Label(root1, text="Last name")
    paragraph2.place(x=250, y=40)
    e2 = Entry(root1, text="")
    e2.place(x=250, y=59)
    paragraph3 = Label(root1, text="Phone number")
    paragraph3.place(x=25, y=90)
    e3 = Entry(root1, text="")
    e3.place(x=25, y=110)
    pargraph4 = Label(root1, text="Address")
    pargraph4.place(x=250, y=90)
    e4 = Entry(root1, text="")
    e4.place(x=250, y=110)
    pargraph5 = Label(root1, text="Zip code")
    pargraph5.place(x=25, y=140)
    e5 = Entry(root1, text="")
    e5.place(x=25, y=160)
    pargraph6 = Label(root1, text="City")
    pargraph6.place(x=250, y=140)
    e6 = Entry(root1, text="")
    e6.place(x=250, y=160)
    pargraph7 = Label(root1, text="State")
    pargraph7.place(x=25, y=190)
    e7 = Entry(root1, text="")
    e7.place(x=25, y=210)
    pargraph8 = Button(root1, text="Clear", command=infosearch)
    pargraph8.place(x=25, y=300)
    myboutton = Button(root1, text="Save the info in file", command=saveinfo)
    myboutton.place(x=25, y=320)
    f.close()
    root1.mainloop()
def saveinfo():
    name = e1.get()
    e1.delete(0, END)
    last = e2.get()
    e2.delete(0, END)
    phone = e3.get()
    e3.delete(0, END)
    address = e4.get()
    e4.delete(0, END)
    zip = e5.get()
    e5.delete(0, END)
    city = e6.get()
    e6.delete(0, END)
    state = e7.get()
    e7.delete(0, END)
    chose(phone,city,state,address,name,last,zip)
    
def chose(phone,city,state,address,name,last,zip):
    f = open('name.txt', 'a')
    if phone == "" or city == "" or state == "" or address == "" or name == "" or last == "":
        def delete():
            roo2.destroy()
        roo2 = Tk()
        roo2.geometry(
            "250x100+400+200")
        error = Label(roo2, text="Please fill out everything(or type none) ")
        error.pack()
        errorbut = Button(roo2, text="OK",command = delete)
        errorbut.pack()
        roo2.mainloop()
    else:
        f.write("\nName\n")
        f.write(name)
        f.write("\nLast\n")
        f.write(last)
        f.write("\nphone\n")
        f.write(phone)
        f.write("\naddress\n")
        f.write(address)
        f.write("\ncity\n")
        f.write(city)
        f.write("\nState\n")
        f.write(state)
        f.write("\nzip\n")
        f.write(zip)
    f.close()



root = Tk()
f = open('name.txt', 'a')
root.geometry(
    "500x500+400+100")  # the window size geometry("window width x window height + position right + position down")
root.title("Soda machine")
Title = Label(root, text="Client Information")
Title.pack()  # put in the middle
Paragraph1 = Label(root, text="\nFirst name\n")
Paragraph1.place(x=25, y=25)
e1 = Entry(root, text="")
e1.place(x=25, y=60)  # can change stuff place
paragraph2 = Label(root, text="Last name")
paragraph2.place(x=250, y=40)
e2 = Entry(root, text="")
e2.place(x=250, y=59)
paragraph3 = Label(root, text="Phone number")
paragraph3.place(x=25, y=90)
e3 = Entry(root, text="")
e3.place(x=25, y=110)
pargraph4 = Label(root, text="Address")
pargraph4.place(x=250, y=90)
e4 = Entry(root, text="")
e4.place(x=250, y=110)
pargraph5 = Label(root, text="Zip code")
pargraph5.place(x=25, y=140)
e5 = Entry(root, text="")
e5.place(x=25, y=160)
pargraph6 = Label(root, text="City")
pargraph6.place(x=250, y=140)
e6 = Entry(root, text="")
e6.place(x=250, y=160)
pargraph7 = Label(root, text="State")
pargraph7.place(x=25, y=190)
e7 = Entry(root, text="")
e7.place(x=25, y=210)
pargraph8 = Button(root, text="Clear", command=infosearch)
pargraph8.place(x=25, y=300)
myboutton = Button(root, text="Save the info in file", command=saveinfo)
myboutton.place(x=25, y=320)
f.close()
root.mainloop()
